// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupviewgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// GroupViewGrant is the model entity for the GroupViewGrant schema.
type GroupViewGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// GrantedByUserID holds the value of the "granted_by_user_id" field.
	GrantedByUserID int64 `json:"granted_by_user_id,omitempty"`
	// GrantedAt holds the value of the "granted_at" field.
	GrantedAt time.Time `json:"granted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupViewGrantQuery when eager-loading is set.
	Edges        GroupViewGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupViewGrantEdges holds the relations/edges for other nodes in the graph.
type GroupViewGrantEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupViewGrantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupViewGrantEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupViewGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupviewgrant.FieldID, groupviewgrant.FieldUserID, groupviewgrant.FieldGroupID, groupviewgrant.FieldGrantedByUserID:
			values[i] = new(sql.NullInt64)
		case groupviewgrant.FieldCreatedAt, groupviewgrant.FieldUpdatedAt, groupviewgrant.FieldDeletedAt, groupviewgrant.FieldGrantedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupViewGrant fields.
func (_m *GroupViewGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupviewgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupviewgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case groupviewgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case groupviewgrant.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case groupviewgrant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case groupviewgrant.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case groupviewgrant.FieldGrantedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_user_id", values[i])
			} else if value.Valid {
				_m.GrantedByUserID = value.Int64
			}
		case groupviewgrant.FieldGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field granted_at", values[i])
			} else if value.Valid {
				_m.GrantedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupViewGrant.
// This includes values selected through modifiers, order, etc.
func (_m *GroupViewGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the GroupViewGrant entity.
func (_m *GroupViewGrant) QueryUser() *UserQuery {
	return NewGroupViewGrantClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the GroupViewGrant entity.
func (_m *GroupViewGrant) QueryGroup() *GroupQuery {
	return NewGroupViewGrantClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this GroupViewGrant.
// Note that you need to call GroupViewGrant.Unwrap() before calling this method if this GroupViewGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupViewGrant) Update() *GroupViewGrantUpdateOne {
	return NewGroupViewGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupViewGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupViewGrant) Unwrap() *GroupViewGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupViewGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupViewGrant) String() string {
	var builder strings.Builder
	builder.WriteString("GroupViewGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("granted_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantedByUserID))
	builder.WriteString(", ")
	builder.WriteString("granted_at=")
	builder.WriteString(_m.GrantedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GroupViewGrants is a parsable slice of GroupViewGrant.
type GroupViewGrants []*GroupViewGrant
