// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupviewgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// GroupViewGrantCreate is the builder for creating a GroupViewGrant entity.
type GroupViewGrantCreate struct {
	config
	mutation *GroupViewGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupViewGrantCreate) SetCreatedAt(v time.Time) *GroupViewGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupViewGrantCreate) SetNillableCreatedAt(v *time.Time) *GroupViewGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupViewGrantCreate) SetUpdatedAt(v time.Time) *GroupViewGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupViewGrantCreate) SetNillableUpdatedAt(v *time.Time) *GroupViewGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *GroupViewGrantCreate) SetDeletedAt(v time.Time) *GroupViewGrantCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *GroupViewGrantCreate) SetNillableDeletedAt(v *time.Time) *GroupViewGrantCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GroupViewGrantCreate) SetUserID(v int64) *GroupViewGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupViewGrantCreate) SetGroupID(v int64) *GroupViewGrantCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (_c *GroupViewGrantCreate) SetGrantedByUserID(v int64) *GroupViewGrantCreate {
	_c.mutation.SetGrantedByUserID(v)
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *GroupViewGrantCreate) SetGrantedAt(v time.Time) *GroupViewGrantCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *GroupViewGrantCreate) SetNillableGrantedAt(v *time.Time) *GroupViewGrantCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *GroupViewGrantCreate) SetUser(v *User) *GroupViewGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupViewGrantCreate) SetGroup(v *Group) *GroupViewGrantCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupViewGrantMutation object of the builder.
func (_c *GroupViewGrantCreate) Mutation() *GroupViewGrantMutation {
	return _c.mutation
}

// Save creates the GroupViewGrant in the database.
func (_c *GroupViewGrantCreate) Save(ctx context.Context) (*GroupViewGrant, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupViewGrantCreate) SaveX(ctx context.Context) *GroupViewGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupViewGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupViewGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupViewGrantCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if groupviewgrant.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized groupviewgrant.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := groupviewgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if groupviewgrant.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized groupviewgrant.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := groupviewgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		if groupviewgrant.DefaultGrantedAt == nil {
			return fmt.Errorf("ent: uninitialized groupviewgrant.DefaultGrantedAt (forgotten import ent/runtime?)")
		}
		v := groupviewgrant.DefaultGrantedAt()
		_c.mutation.SetGrantedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupViewGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupViewGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupViewGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "GroupViewGrant.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupViewGrant.group_id"`)}
	}
	if _, ok := _c.mutation.GrantedByUserID(); !ok {
		return &ValidationError{Name: "granted_by_user_id", err: errors.New(`ent: missing required field "GroupViewGrant.granted_by_user_id"`)}
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		return &ValidationError{Name: "granted_at", err: errors.New(`ent: missing required field "GroupViewGrant.granted_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "GroupViewGrant.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupViewGrant.group"`)}
	}
	return nil
}

func (_c *GroupViewGrantCreate) sqlSave(ctx context.Context) (*GroupViewGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupViewGrantCreate) createSpec() (*GroupViewGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupViewGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupviewgrant.Table, sqlgraph.NewFieldSpec(groupviewgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupviewgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupviewgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(groupviewgrant.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.GrantedByUserID(); ok {
		_spec.SetField(groupviewgrant.FieldGrantedByUserID, field.TypeInt64, value)
		_node.GrantedByUserID = value
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(groupviewgrant.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.UserTable,
			Columns: []string{groupviewgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.GroupTable,
			Columns: []string{groupviewgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupViewGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupViewGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupViewGrantCreate) OnConflict(opts ...sql.ConflictOption) *GroupViewGrantUpsertOne {
	_c.conflict = opts
	return &GroupViewGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupViewGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupViewGrantCreate) OnConflictColumns(columns ...string) *GroupViewGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupViewGrantUpsertOne{
		create: _c,
	}
}

type (
	// GroupViewGrantUpsertOne is the builder for "upsert"-ing
	//  one GroupViewGrant node.
	GroupViewGrantUpsertOne struct {
		create *GroupViewGrantCreate
	}

	// GroupViewGrantUpsert is the "OnConflict" setter.
	GroupViewGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupViewGrantUpsert) SetUpdatedAt(v time.Time) *GroupViewGrantUpsert {
	u.Set(groupviewgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupViewGrantUpsert) UpdateUpdatedAt() *GroupViewGrantUpsert {
	u.SetExcluded(groupviewgrant.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GroupViewGrantUpsert) SetDeletedAt(v time.Time) *GroupViewGrantUpsert {
	u.Set(groupviewgrant.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GroupViewGrantUpsert) UpdateDeletedAt() *GroupViewGrantUpsert {
	u.SetExcluded(groupviewgrant.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GroupViewGrantUpsert) ClearDeletedAt() *GroupViewGrantUpsert {
	u.SetNull(groupviewgrant.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *GroupViewGrantUpsert) SetUserID(v int64) *GroupViewGrantUpsert {
	u.Set(groupviewgrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsert) UpdateUserID() *GroupViewGrantUpsert {
	u.SetExcluded(groupviewgrant.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupViewGrantUpsert) SetGroupID(v int64) *GroupViewGrantUpsert {
	u.Set(groupviewgrant.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsert) UpdateGroupID() *GroupViewGrantUpsert {
	u.SetExcluded(groupviewgrant.FieldGroupID)
	return u
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (u *GroupViewGrantUpsert) SetGrantedByUserID(v int64) *GroupViewGrantUpsert {
	u.Set(groupviewgrant.FieldGrantedByUserID, v)
	return u
}

// UpdateGrantedByUserID sets the "granted_by_user_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsert) UpdateGrantedByUserID() *GroupViewGrantUpsert {
	u.SetExcluded(groupviewgrant.FieldGrantedByUserID)
	return u
}

// AddGrantedByUserID adds v to the "granted_by_user_id" field.
func (u *GroupViewGrantUpsert) AddGrantedByUserID(v int64) *GroupViewGrantUpsert {
	u.Add(groupviewgrant.FieldGrantedByUserID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupViewGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupViewGrantUpsertOne) UpdateNewValues() *GroupViewGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupviewgrant.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.GrantedAt(); exists {
			s.SetIgnore(groupviewgrant.FieldGrantedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupViewGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupViewGrantUpsertOne) Ignore() *GroupViewGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupViewGrantUpsertOne) DoNothing() *GroupViewGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupViewGrantCreate.OnConflict
// documentation for more info.
func (u *GroupViewGrantUpsertOne) Update(set func(*GroupViewGrantUpsert)) *GroupViewGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupViewGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupViewGrantUpsertOne) SetUpdatedAt(v time.Time) *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupViewGrantUpsertOne) UpdateUpdatedAt() *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GroupViewGrantUpsertOne) SetDeletedAt(v time.Time) *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GroupViewGrantUpsertOne) UpdateDeletedAt() *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GroupViewGrantUpsertOne) ClearDeletedAt() *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *GroupViewGrantUpsertOne) SetUserID(v int64) *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsertOne) UpdateUserID() *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupViewGrantUpsertOne) SetGroupID(v int64) *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsertOne) UpdateGroupID() *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (u *GroupViewGrantUpsertOne) SetGrantedByUserID(v int64) *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetGrantedByUserID(v)
	})
}

// AddGrantedByUserID adds v to the "granted_by_user_id" field.
func (u *GroupViewGrantUpsertOne) AddGrantedByUserID(v int64) *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.AddGrantedByUserID(v)
	})
}

// UpdateGrantedByUserID sets the "granted_by_user_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsertOne) UpdateGrantedByUserID() *GroupViewGrantUpsertOne {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateGrantedByUserID()
	})
}

// Exec executes the query.
func (u *GroupViewGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupViewGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupViewGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupViewGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupViewGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupViewGrantCreateBulk is the builder for creating many GroupViewGrant entities in bulk.
type GroupViewGrantCreateBulk struct {
	config
	err      error
	builders []*GroupViewGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupViewGrant entities in the database.
func (_c *GroupViewGrantCreateBulk) Save(ctx context.Context) ([]*GroupViewGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupViewGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupViewGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupViewGrantCreateBulk) SaveX(ctx context.Context) []*GroupViewGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupViewGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupViewGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupViewGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupViewGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupViewGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupViewGrantUpsertBulk {
	_c.conflict = opts
	return &GroupViewGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupViewGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupViewGrantCreateBulk) OnConflictColumns(columns ...string) *GroupViewGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupViewGrantUpsertBulk{
		create: _c,
	}
}

// GroupViewGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupViewGrant nodes.
type GroupViewGrantUpsertBulk struct {
	create *GroupViewGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupViewGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupViewGrantUpsertBulk) UpdateNewValues() *GroupViewGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupviewgrant.FieldCreatedAt)
			}
			if _, exists := b.mutation.GrantedAt(); exists {
				s.SetIgnore(groupviewgrant.FieldGrantedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupViewGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupViewGrantUpsertBulk) Ignore() *GroupViewGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupViewGrantUpsertBulk) DoNothing() *GroupViewGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupViewGrantCreateBulk.OnConflict
// documentation for more info.
func (u *GroupViewGrantUpsertBulk) Update(set func(*GroupViewGrantUpsert)) *GroupViewGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupViewGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupViewGrantUpsertBulk) SetUpdatedAt(v time.Time) *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupViewGrantUpsertBulk) UpdateUpdatedAt() *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GroupViewGrantUpsertBulk) SetDeletedAt(v time.Time) *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GroupViewGrantUpsertBulk) UpdateDeletedAt() *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GroupViewGrantUpsertBulk) ClearDeletedAt() *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *GroupViewGrantUpsertBulk) SetUserID(v int64) *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsertBulk) UpdateUserID() *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupViewGrantUpsertBulk) SetGroupID(v int64) *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsertBulk) UpdateGroupID() *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (u *GroupViewGrantUpsertBulk) SetGrantedByUserID(v int64) *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.SetGrantedByUserID(v)
	})
}

// AddGrantedByUserID adds v to the "granted_by_user_id" field.
func (u *GroupViewGrantUpsertBulk) AddGrantedByUserID(v int64) *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.AddGrantedByUserID(v)
	})
}

// UpdateGrantedByUserID sets the "granted_by_user_id" field to the value that was provided on create.
func (u *GroupViewGrantUpsertBulk) UpdateGrantedByUserID() *GroupViewGrantUpsertBulk {
	return u.Update(func(s *GroupViewGrantUpsert) {
		s.UpdateGrantedByUserID()
	})
}

// Exec executes the query.
func (u *GroupViewGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupViewGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupViewGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupViewGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
