// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupviewgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// GroupViewGrantUpdate is the builder for updating GroupViewGrant entities.
type GroupViewGrantUpdate struct {
	config
	hooks    []Hook
	mutation *GroupViewGrantMutation
}

// Where appends a list predicates to the GroupViewGrantUpdate builder.
func (_u *GroupViewGrantUpdate) Where(ps ...predicate.GroupViewGrant) *GroupViewGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupViewGrantUpdate) SetUpdatedAt(v time.Time) *GroupViewGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GroupViewGrantUpdate) SetDeletedAt(v time.Time) *GroupViewGrantUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GroupViewGrantUpdate) SetNillableDeletedAt(v *time.Time) *GroupViewGrantUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GroupViewGrantUpdate) ClearDeletedAt() *GroupViewGrantUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GroupViewGrantUpdate) SetUserID(v int64) *GroupViewGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GroupViewGrantUpdate) SetNillableUserID(v *int64) *GroupViewGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupViewGrantUpdate) SetGroupID(v int64) *GroupViewGrantUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupViewGrantUpdate) SetNillableGroupID(v *int64) *GroupViewGrantUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (_u *GroupViewGrantUpdate) SetGrantedByUserID(v int64) *GroupViewGrantUpdate {
	_u.mutation.ResetGrantedByUserID()
	_u.mutation.SetGrantedByUserID(v)
	return _u
}

// SetNillableGrantedByUserID sets the "granted_by_user_id" field if the given value is not nil.
func (_u *GroupViewGrantUpdate) SetNillableGrantedByUserID(v *int64) *GroupViewGrantUpdate {
	if v != nil {
		_u.SetGrantedByUserID(*v)
	}
	return _u
}

// AddGrantedByUserID adds value to the "granted_by_user_id" field.
func (_u *GroupViewGrantUpdate) AddGrantedByUserID(v int64) *GroupViewGrantUpdate {
	_u.mutation.AddGrantedByUserID(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GroupViewGrantUpdate) SetUser(v *User) *GroupViewGrantUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupViewGrantUpdate) SetGroup(v *Group) *GroupViewGrantUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupViewGrantMutation object of the builder.
func (_u *GroupViewGrantUpdate) Mutation() *GroupViewGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GroupViewGrantUpdate) ClearUser() *GroupViewGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupViewGrantUpdate) ClearGroup() *GroupViewGrantUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupViewGrantUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupViewGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupViewGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupViewGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupViewGrantUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if groupviewgrant.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized groupviewgrant.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := groupviewgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupViewGrantUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupViewGrant.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupViewGrant.group"`)
	}
	return nil
}

func (_u *GroupViewGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupviewgrant.Table, groupviewgrant.Columns, sqlgraph.NewFieldSpec(groupviewgrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupviewgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(groupviewgrant.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(groupviewgrant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GrantedByUserID(); ok {
		_spec.SetField(groupviewgrant.FieldGrantedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGrantedByUserID(); ok {
		_spec.AddField(groupviewgrant.FieldGrantedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.UserTable,
			Columns: []string{groupviewgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.UserTable,
			Columns: []string{groupviewgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.GroupTable,
			Columns: []string{groupviewgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.GroupTable,
			Columns: []string{groupviewgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupviewgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupViewGrantUpdateOne is the builder for updating a single GroupViewGrant entity.
type GroupViewGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupViewGrantMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupViewGrantUpdateOne) SetUpdatedAt(v time.Time) *GroupViewGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GroupViewGrantUpdateOne) SetDeletedAt(v time.Time) *GroupViewGrantUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GroupViewGrantUpdateOne) SetNillableDeletedAt(v *time.Time) *GroupViewGrantUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GroupViewGrantUpdateOne) ClearDeletedAt() *GroupViewGrantUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GroupViewGrantUpdateOne) SetUserID(v int64) *GroupViewGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GroupViewGrantUpdateOne) SetNillableUserID(v *int64) *GroupViewGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupViewGrantUpdateOne) SetGroupID(v int64) *GroupViewGrantUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupViewGrantUpdateOne) SetNillableGroupID(v *int64) *GroupViewGrantUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (_u *GroupViewGrantUpdateOne) SetGrantedByUserID(v int64) *GroupViewGrantUpdateOne {
	_u.mutation.ResetGrantedByUserID()
	_u.mutation.SetGrantedByUserID(v)
	return _u
}

// SetNillableGrantedByUserID sets the "granted_by_user_id" field if the given value is not nil.
func (_u *GroupViewGrantUpdateOne) SetNillableGrantedByUserID(v *int64) *GroupViewGrantUpdateOne {
	if v != nil {
		_u.SetGrantedByUserID(*v)
	}
	return _u
}

// AddGrantedByUserID adds value to the "granted_by_user_id" field.
func (_u *GroupViewGrantUpdateOne) AddGrantedByUserID(v int64) *GroupViewGrantUpdateOne {
	_u.mutation.AddGrantedByUserID(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *GroupViewGrantUpdateOne) SetUser(v *User) *GroupViewGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupViewGrantUpdateOne) SetGroup(v *Group) *GroupViewGrantUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupViewGrantMutation object of the builder.
func (_u *GroupViewGrantUpdateOne) Mutation() *GroupViewGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GroupViewGrantUpdateOne) ClearUser() *GroupViewGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupViewGrantUpdateOne) ClearGroup() *GroupViewGrantUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the GroupViewGrantUpdate builder.
func (_u *GroupViewGrantUpdateOne) Where(ps ...predicate.GroupViewGrant) *GroupViewGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupViewGrantUpdateOne) Select(field string, fields ...string) *GroupViewGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupViewGrant entity.
func (_u *GroupViewGrantUpdateOne) Save(ctx context.Context) (*GroupViewGrant, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupViewGrantUpdateOne) SaveX(ctx context.Context) *GroupViewGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupViewGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupViewGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupViewGrantUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if groupviewgrant.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized groupviewgrant.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := groupviewgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupViewGrantUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupViewGrant.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupViewGrant.group"`)
	}
	return nil
}

func (_u *GroupViewGrantUpdateOne) sqlSave(ctx context.Context) (_node *GroupViewGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupviewgrant.Table, groupviewgrant.Columns, sqlgraph.NewFieldSpec(groupviewgrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupViewGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupviewgrant.FieldID)
		for _, f := range fields {
			if !groupviewgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupviewgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupviewgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(groupviewgrant.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(groupviewgrant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GrantedByUserID(); ok {
		_spec.SetField(groupviewgrant.FieldGrantedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGrantedByUserID(); ok {
		_spec.AddField(groupviewgrant.FieldGrantedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.UserTable,
			Columns: []string{groupviewgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.UserTable,
			Columns: []string{groupviewgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.GroupTable,
			Columns: []string{groupviewgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupviewgrant.GroupTable,
			Columns: []string{groupviewgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupViewGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupviewgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
