// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usergroupqosusage"
)

// UserGroupQoSUsageCreate is the builder for creating a UserGroupQoSUsage entity.
type UserGroupQoSUsageCreate struct {
	config
	mutation *UserGroupQoSUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserGroupQoSUsageCreate) SetCreatedAt(v time.Time) *UserGroupQoSUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableCreatedAt(v *time.Time) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserGroupQoSUsageCreate) SetUpdatedAt(v time.Time) *UserGroupQoSUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableUpdatedAt(v *time.Time) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserGroupQoSUsageCreate) SetDeletedAt(v time.Time) *UserGroupQoSUsageCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableDeletedAt(v *time.Time) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserGroupQoSUsageCreate) SetUserID(v int64) *UserGroupQoSUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserGroupQoSUsageCreate) SetGroupID(v int64) *UserGroupQoSUsageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *UserGroupQoSUsageCreate) SetDailyUsageUsd(v float64) *UserGroupQoSUsageCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableDailyUsageUsd(v *float64) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *UserGroupQoSUsageCreate) SetWeeklyUsageUsd(v float64) *UserGroupQoSUsageCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableWeeklyUsageUsd(v *float64) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *UserGroupQoSUsageCreate) SetMonthlyUsageUsd(v float64) *UserGroupQoSUsageCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableMonthlyUsageUsd(v *float64) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *UserGroupQoSUsageCreate) SetDailyWindowStart(v time.Time) *UserGroupQoSUsageCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableDailyWindowStart(v *time.Time) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *UserGroupQoSUsageCreate) SetWeeklyWindowStart(v time.Time) *UserGroupQoSUsageCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableWeeklyWindowStart(v *time.Time) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *UserGroupQoSUsageCreate) SetMonthlyWindowStart(v time.Time) *UserGroupQoSUsageCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *UserGroupQoSUsageCreate) SetNillableMonthlyWindowStart(v *time.Time) *UserGroupQoSUsageCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// Mutation returns the UserGroupQoSUsageMutation object of the builder.
func (_c *UserGroupQoSUsageCreate) Mutation() *UserGroupQoSUsageMutation {
	return _c.mutation
}

// Save creates the UserGroupQoSUsage in the database.
func (_c *UserGroupQoSUsageCreate) Save(ctx context.Context) (*UserGroupQoSUsage, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserGroupQoSUsageCreate) SaveX(ctx context.Context) *UserGroupQoSUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupQoSUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupQoSUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserGroupQoSUsageCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usergroupqosusage.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupqosusage.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupqosusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usergroupqosusage.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupqosusage.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupqosusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := usergroupqosusage.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := usergroupqosusage.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := usergroupqosusage.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserGroupQoSUsageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserGroupQoSUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserGroupQoSUsage.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserGroupQoSUsage.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserGroupQoSUsage.group_id"`)}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "UserGroupQoSUsage.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "UserGroupQoSUsage.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "UserGroupQoSUsage.monthly_usage_usd"`)}
	}
	return nil
}

func (_c *UserGroupQoSUsageCreate) sqlSave(ctx context.Context) (*UserGroupQoSUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserGroupQoSUsageCreate) createSpec() (*UserGroupQoSUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &UserGroupQoSUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usergroupqosusage.Table, sqlgraph.NewFieldSpec(usergroupqosusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usergroupqosusage.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usergroupqosusage.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupQoSUsage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupQoSUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupQoSUsageCreate) OnConflict(opts ...sql.ConflictOption) *UserGroupQoSUsageUpsertOne {
	_c.conflict = opts
	return &UserGroupQoSUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupQoSUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupQoSUsageCreate) OnConflictColumns(columns ...string) *UserGroupQoSUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupQoSUsageUpsertOne{
		create: _c,
	}
}

type (
	// UserGroupQoSUsageUpsertOne is the builder for "upsert"-ing
	//  one UserGroupQoSUsage node.
	UserGroupQoSUsageUpsertOne struct {
		create *UserGroupQoSUsageCreate
	}

	// UserGroupQoSUsageUpsert is the "OnConflict" setter.
	UserGroupQoSUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupQoSUsageUpsert) SetUpdatedAt(v time.Time) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateUpdatedAt() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupQoSUsageUpsert) SetDeletedAt(v time.Time) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateDeletedAt() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupQoSUsageUpsert) ClearDeletedAt() *UserGroupQoSUsageUpsert {
	u.SetNull(usergroupqosusage.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserGroupQoSUsageUpsert) SetUserID(v int64) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateUserID() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupQoSUsageUpsert) AddUserID(v int64) *UserGroupQoSUsageUpsert {
	u.Add(usergroupqosusage.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupQoSUsageUpsert) SetGroupID(v int64) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateGroupID() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupQoSUsageUpsert) AddGroupID(v int64) *UserGroupQoSUsageUpsert {
	u.Add(usergroupqosusage.FieldGroupID, v)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserGroupQoSUsageUpsert) SetDailyUsageUsd(v float64) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateDailyUsageUsd() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserGroupQoSUsageUpsert) AddDailyUsageUsd(v float64) *UserGroupQoSUsageUpsert {
	u.Add(usergroupqosusage.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserGroupQoSUsageUpsert) SetWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateWeeklyUsageUsd() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserGroupQoSUsageUpsert) AddWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpsert {
	u.Add(usergroupqosusage.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserGroupQoSUsageUpsert) SetMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateMonthlyUsageUsd() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserGroupQoSUsageUpsert) AddMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpsert {
	u.Add(usergroupqosusage.FieldMonthlyUsageUsd, v)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserGroupQoSUsageUpsert) SetDailyWindowStart(v time.Time) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateDailyWindowStart() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserGroupQoSUsageUpsert) ClearDailyWindowStart() *UserGroupQoSUsageUpsert {
	u.SetNull(usergroupqosusage.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserGroupQoSUsageUpsert) SetWeeklyWindowStart(v time.Time) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateWeeklyWindowStart() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserGroupQoSUsageUpsert) ClearWeeklyWindowStart() *UserGroupQoSUsageUpsert {
	u.SetNull(usergroupqosusage.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserGroupQoSUsageUpsert) SetMonthlyWindowStart(v time.Time) *UserGroupQoSUsageUpsert {
	u.Set(usergroupqosusage.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsert) UpdateMonthlyWindowStart() *UserGroupQoSUsageUpsert {
	u.SetExcluded(usergroupqosusage.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserGroupQoSUsageUpsert) ClearMonthlyWindowStart() *UserGroupQoSUsageUpsert {
	u.SetNull(usergroupqosusage.FieldMonthlyWindowStart)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserGroupQoSUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupQoSUsageUpsertOne) UpdateNewValues() *UserGroupQoSUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usergroupqosusage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupQoSUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserGroupQoSUsageUpsertOne) Ignore() *UserGroupQoSUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupQoSUsageUpsertOne) DoNothing() *UserGroupQoSUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupQoSUsageCreate.OnConflict
// documentation for more info.
func (u *UserGroupQoSUsageUpsertOne) Update(set func(*UserGroupQoSUsageUpsert)) *UserGroupQoSUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupQoSUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupQoSUsageUpsertOne) SetUpdatedAt(v time.Time) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateUpdatedAt() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupQoSUsageUpsertOne) SetDeletedAt(v time.Time) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateDeletedAt() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupQoSUsageUpsertOne) ClearDeletedAt() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGroupQoSUsageUpsertOne) SetUserID(v int64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupQoSUsageUpsertOne) AddUserID(v int64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateUserID() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupQoSUsageUpsertOne) SetGroupID(v int64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupQoSUsageUpsertOne) AddGroupID(v int64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateGroupID() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserGroupQoSUsageUpsertOne) SetDailyUsageUsd(v float64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserGroupQoSUsageUpsertOne) AddDailyUsageUsd(v float64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateDailyUsageUsd() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertOne) SetWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertOne) AddWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateWeeklyUsageUsd() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertOne) SetMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertOne) AddMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateMonthlyUsageUsd() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserGroupQoSUsageUpsertOne) SetDailyWindowStart(v time.Time) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateDailyWindowStart() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserGroupQoSUsageUpsertOne) ClearDailyWindowStart() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserGroupQoSUsageUpsertOne) SetWeeklyWindowStart(v time.Time) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateWeeklyWindowStart() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserGroupQoSUsageUpsertOne) ClearWeeklyWindowStart() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserGroupQoSUsageUpsertOne) SetMonthlyWindowStart(v time.Time) *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertOne) UpdateMonthlyWindowStart() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserGroupQoSUsageUpsertOne) ClearMonthlyWindowStart() *UserGroupQoSUsageUpsertOne {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// Exec executes the query.
func (u *UserGroupQoSUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupQoSUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupQoSUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserGroupQoSUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserGroupQoSUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserGroupQoSUsageCreateBulk is the builder for creating many UserGroupQoSUsage entities in bulk.
type UserGroupQoSUsageCreateBulk struct {
	config
	err      error
	builders []*UserGroupQoSUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the UserGroupQoSUsage entities in the database.
func (_c *UserGroupQoSUsageCreateBulk) Save(ctx context.Context) ([]*UserGroupQoSUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserGroupQoSUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserGroupQoSUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserGroupQoSUsageCreateBulk) SaveX(ctx context.Context) []*UserGroupQoSUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupQoSUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupQoSUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupQoSUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupQoSUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupQoSUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserGroupQoSUsageUpsertBulk {
	_c.conflict = opts
	return &UserGroupQoSUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupQoSUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupQoSUsageCreateBulk) OnConflictColumns(columns ...string) *UserGroupQoSUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupQoSUsageUpsertBulk{
		create: _c,
	}
}

// UserGroupQoSUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of UserGroupQoSUsage nodes.
type UserGroupQoSUsageUpsertBulk struct {
	create *UserGroupQoSUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserGroupQoSUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupQoSUsageUpsertBulk) UpdateNewValues() *UserGroupQoSUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usergroupqosusage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupQoSUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserGroupQoSUsageUpsertBulk) Ignore() *UserGroupQoSUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupQoSUsageUpsertBulk) DoNothing() *UserGroupQoSUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupQoSUsageCreateBulk.OnConflict
// documentation for more info.
func (u *UserGroupQoSUsageUpsertBulk) Update(set func(*UserGroupQoSUsageUpsert)) *UserGroupQoSUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupQoSUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupQoSUsageUpsertBulk) SetUpdatedAt(v time.Time) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateUpdatedAt() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserGroupQoSUsageUpsertBulk) SetDeletedAt(v time.Time) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateDeletedAt() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserGroupQoSUsageUpsertBulk) ClearDeletedAt() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserGroupQoSUsageUpsertBulk) SetUserID(v int64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupQoSUsageUpsertBulk) AddUserID(v int64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateUserID() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupQoSUsageUpsertBulk) SetGroupID(v int64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupQoSUsageUpsertBulk) AddGroupID(v int64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateGroupID() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserGroupQoSUsageUpsertBulk) SetDailyUsageUsd(v float64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserGroupQoSUsageUpsertBulk) AddDailyUsageUsd(v float64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateDailyUsageUsd() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertBulk) SetWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertBulk) AddWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateWeeklyUsageUsd() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertBulk) SetMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserGroupQoSUsageUpsertBulk) AddMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateMonthlyUsageUsd() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserGroupQoSUsageUpsertBulk) SetDailyWindowStart(v time.Time) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateDailyWindowStart() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserGroupQoSUsageUpsertBulk) ClearDailyWindowStart() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserGroupQoSUsageUpsertBulk) SetWeeklyWindowStart(v time.Time) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateWeeklyWindowStart() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserGroupQoSUsageUpsertBulk) ClearWeeklyWindowStart() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserGroupQoSUsageUpsertBulk) SetMonthlyWindowStart(v time.Time) *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserGroupQoSUsageUpsertBulk) UpdateMonthlyWindowStart() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserGroupQoSUsageUpsertBulk) ClearMonthlyWindowStart() *UserGroupQoSUsageUpsertBulk {
	return u.Update(func(s *UserGroupQoSUsageUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// Exec executes the query.
func (u *UserGroupQoSUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserGroupQoSUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupQoSUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupQoSUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
