// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usergroupqosusage"
)

// UserGroupQoSUsageDelete is the builder for deleting a UserGroupQoSUsage entity.
type UserGroupQoSUsageDelete struct {
	config
	hooks    []Hook
	mutation *UserGroupQoSUsageMutation
}

// Where appends a list predicates to the UserGroupQoSUsageDelete builder.
func (_d *UserGroupQoSUsageDelete) Where(ps ...predicate.UserGroupQoSUsage) *UserGroupQoSUsageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserGroupQoSUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserGroupQoSUsageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserGroupQoSUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usergroupqosusage.Table, sqlgraph.NewFieldSpec(usergroupqosusage.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserGroupQoSUsageDeleteOne is the builder for deleting a single UserGroupQoSUsage entity.
type UserGroupQoSUsageDeleteOne struct {
	_d *UserGroupQoSUsageDelete
}

// Where appends a list predicates to the UserGroupQoSUsageDelete builder.
func (_d *UserGroupQoSUsageDeleteOne) Where(ps ...predicate.UserGroupQoSUsage) *UserGroupQoSUsageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserGroupQoSUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usergroupqosusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserGroupQoSUsageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
