// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usergroupqosusage"
)

// UserGroupQoSUsageUpdate is the builder for updating UserGroupQoSUsage entities.
type UserGroupQoSUsageUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupQoSUsageMutation
}

// Where appends a list predicates to the UserGroupQoSUsageUpdate builder.
func (_u *UserGroupQoSUsageUpdate) Where(ps ...predicate.UserGroupQoSUsage) *UserGroupQoSUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupQoSUsageUpdate) SetUpdatedAt(v time.Time) *UserGroupQoSUsageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGroupQoSUsageUpdate) SetDeletedAt(v time.Time) *UserGroupQoSUsageUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableDeletedAt(v *time.Time) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGroupQoSUsageUpdate) ClearDeletedAt() *UserGroupQoSUsageUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupQoSUsageUpdate) SetUserID(v int64) *UserGroupQoSUsageUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableUserID(v *int64) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserGroupQoSUsageUpdate) AddUserID(v int64) *UserGroupQoSUsageUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupQoSUsageUpdate) SetGroupID(v int64) *UserGroupQoSUsageUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableGroupID(v *int64) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGroupQoSUsageUpdate) AddGroupID(v int64) *UserGroupQoSUsageUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserGroupQoSUsageUpdate) SetDailyUsageUsd(v float64) *UserGroupQoSUsageUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableDailyUsageUsd(v *float64) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserGroupQoSUsageUpdate) AddDailyUsageUsd(v float64) *UserGroupQoSUsageUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdate) SetWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableWeeklyUsageUsd(v *float64) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdate) AddWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdate) SetMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableMonthlyUsageUsd(v *float64) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdate) AddMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserGroupQoSUsageUpdate) SetDailyWindowStart(v time.Time) *UserGroupQoSUsageUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableDailyWindowStart(v *time.Time) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserGroupQoSUsageUpdate) ClearDailyWindowStart() *UserGroupQoSUsageUpdate {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserGroupQoSUsageUpdate) SetWeeklyWindowStart(v time.Time) *UserGroupQoSUsageUpdate {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableWeeklyWindowStart(v *time.Time) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserGroupQoSUsageUpdate) ClearWeeklyWindowStart() *UserGroupQoSUsageUpdate {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserGroupQoSUsageUpdate) SetMonthlyWindowStart(v time.Time) *UserGroupQoSUsageUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdate) SetNillableMonthlyWindowStart(v *time.Time) *UserGroupQoSUsageUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserGroupQoSUsageUpdate) ClearMonthlyWindowStart() *UserGroupQoSUsageUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// Mutation returns the UserGroupQoSUsageMutation object of the builder.
func (_u *UserGroupQoSUsageUpdate) Mutation() *UserGroupQoSUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGroupQoSUsageUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupQoSUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGroupQoSUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupQoSUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupQoSUsageUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usergroupqosusage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupqosusage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupqosusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *UserGroupQoSUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usergroupqosusage.Table, usergroupqosusage.Columns, sqlgraph.NewFieldSpec(usergroupqosusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroupqosusage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usergroupqosusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usergroupqosusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergroupqosusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergroupqosusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usergroupqosusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usergroupqosusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usergroupqosusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usergroupqosusage.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usergroupqosusage.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usergroupqosusage.FieldMonthlyWindowStart, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupqosusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGroupQoSUsageUpdateOne is the builder for updating a single UserGroupQoSUsage entity.
type UserGroupQoSUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupQoSUsageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupQoSUsageUpdateOne) SetUpdatedAt(v time.Time) *UserGroupQoSUsageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserGroupQoSUsageUpdateOne) SetDeletedAt(v time.Time) *UserGroupQoSUsageUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableDeletedAt(v *time.Time) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserGroupQoSUsageUpdateOne) ClearDeletedAt() *UserGroupQoSUsageUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupQoSUsageUpdateOne) SetUserID(v int64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableUserID(v *int64) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserGroupQoSUsageUpdateOne) AddUserID(v int64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupQoSUsageUpdateOne) SetGroupID(v int64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableGroupID(v *int64) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGroupQoSUsageUpdateOne) AddGroupID(v int64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserGroupQoSUsageUpdateOne) SetDailyUsageUsd(v float64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableDailyUsageUsd(v *float64) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserGroupQoSUsageUpdateOne) AddDailyUsageUsd(v float64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdateOne) SetWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdateOne) AddWeeklyUsageUsd(v float64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdateOne) SetMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserGroupQoSUsageUpdateOne) AddMonthlyUsageUsd(v float64) *UserGroupQoSUsageUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserGroupQoSUsageUpdateOne) SetDailyWindowStart(v time.Time) *UserGroupQoSUsageUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableDailyWindowStart(v *time.Time) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserGroupQoSUsageUpdateOne) ClearDailyWindowStart() *UserGroupQoSUsageUpdateOne {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserGroupQoSUsageUpdateOne) SetWeeklyWindowStart(v time.Time) *UserGroupQoSUsageUpdateOne {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableWeeklyWindowStart(v *time.Time) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserGroupQoSUsageUpdateOne) ClearWeeklyWindowStart() *UserGroupQoSUsageUpdateOne {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserGroupQoSUsageUpdateOne) SetMonthlyWindowStart(v time.Time) *UserGroupQoSUsageUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserGroupQoSUsageUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *UserGroupQoSUsageUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserGroupQoSUsageUpdateOne) ClearMonthlyWindowStart() *UserGroupQoSUsageUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// Mutation returns the UserGroupQoSUsageMutation object of the builder.
func (_u *UserGroupQoSUsageUpdateOne) Mutation() *UserGroupQoSUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserGroupQoSUsageUpdate builder.
func (_u *UserGroupQoSUsageUpdateOne) Where(ps ...predicate.UserGroupQoSUsage) *UserGroupQoSUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGroupQoSUsageUpdateOne) Select(field string, fields ...string) *UserGroupQoSUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGroupQoSUsage entity.
func (_u *UserGroupQoSUsageUpdateOne) Save(ctx context.Context) (*UserGroupQoSUsage, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupQoSUsageUpdateOne) SaveX(ctx context.Context) *UserGroupQoSUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGroupQoSUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupQoSUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupQoSUsageUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usergroupqosusage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usergroupqosusage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usergroupqosusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *UserGroupQoSUsageUpdateOne) sqlSave(ctx context.Context) (_node *UserGroupQoSUsage, err error) {
	_spec := sqlgraph.NewUpdateSpec(usergroupqosusage.Table, usergroupqosusage.Columns, sqlgraph.NewFieldSpec(usergroupqosusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroupQoSUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroupqosusage.FieldID)
		for _, f := range fields {
			if !usergroupqosusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroupqosusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usergroupqosusage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usergroupqosusage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usergroupqosusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usergroupqosusage.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergroupqosusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergroupqosusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usergroupqosusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usergroupqosusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usergroupqosusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usergroupqosusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usergroupqosusage.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usergroupqosusage.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usergroupqosusage.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usergroupqosusage.FieldMonthlyWindowStart, field.TypeTime)
	}
	_node = &UserGroupQoSUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupqosusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
