// Code generated by ent, DO NOT EDIT.

package groupviewgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldGroupID, v))
}

// GrantedByUserID applies equality check predicate on the "granted_by_user_id" field. It's identical to GrantedByUserIDEQ.
func GrantedByUserID(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldGrantedByUserID, v))
}

// GrantedAt applies equality check predicate on the "granted_at" field. It's identical to GrantedAtEQ.
func GrantedAt(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldGrantedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldGroupID, vs...))
}

// GrantedByUserIDEQ applies the EQ predicate on the "granted_by_user_id" field.
func GrantedByUserIDEQ(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldGrantedByUserID, v))
}

// GrantedByUserIDNEQ applies the NEQ predicate on the "granted_by_user_id" field.
func GrantedByUserIDNEQ(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldGrantedByUserID, v))
}

// GrantedByUserIDIn applies the In predicate on the "granted_by_user_id" field.
func GrantedByUserIDIn(vs ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldGrantedByUserID, vs...))
}

// GrantedByUserIDNotIn applies the NotIn predicate on the "granted_by_user_id" field.
func GrantedByUserIDNotIn(vs ...int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldGrantedByUserID, vs...))
}

// GrantedByUserIDGT applies the GT predicate on the "granted_by_user_id" field.
func GrantedByUserIDGT(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGT(FieldGrantedByUserID, v))
}

// GrantedByUserIDGTE applies the GTE predicate on the "granted_by_user_id" field.
func GrantedByUserIDGTE(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGTE(FieldGrantedByUserID, v))
}

// GrantedByUserIDLT applies the LT predicate on the "granted_by_user_id" field.
func GrantedByUserIDLT(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLT(FieldGrantedByUserID, v))
}

// GrantedByUserIDLTE applies the LTE predicate on the "granted_by_user_id" field.
func GrantedByUserIDLTE(v int64) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLTE(FieldGrantedByUserID, v))
}

// GrantedAtEQ applies the EQ predicate on the "granted_at" field.
func GrantedAtEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedAtNEQ applies the NEQ predicate on the "granted_at" field.
func GrantedAtNEQ(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNEQ(FieldGrantedAt, v))
}

// GrantedAtIn applies the In predicate on the "granted_at" field.
func GrantedAtIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldIn(FieldGrantedAt, vs...))
}

// GrantedAtNotIn applies the NotIn predicate on the "granted_at" field.
func GrantedAtNotIn(vs ...time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldNotIn(FieldGrantedAt, vs...))
}

// GrantedAtGT applies the GT predicate on the "granted_at" field.
func GrantedAtGT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGT(FieldGrantedAt, v))
}

// GrantedAtGTE applies the GTE predicate on the "granted_at" field.
func GrantedAtGTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldGTE(FieldGrantedAt, v))
}

// GrantedAtLT applies the LT predicate on the "granted_at" field.
func GrantedAtLT(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLT(FieldGrantedAt, v))
}

// GrantedAtLTE applies the LTE predicate on the "granted_at" field.
func GrantedAtLTE(v time.Time) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.FieldLTE(FieldGrantedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GroupViewGrant {
	return predicate.GroupViewGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupViewGrant {
	return predicate.GroupViewGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupViewGrant) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupViewGrant) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupViewGrant) predicate.GroupViewGrant {
	return predicate.GroupViewGrant(sql.NotPredicates(p))
}
